# TO-DO replace this with label map
def class_text_to_int(row_label):
    if row_label == 'basketball':
        return 1
    elif row_label == 'Non-overlap':
        return 2
    elif row_label == 'Overlap':
        return 3
    else:
        return None